server:
  port: 9000
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/transcation?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
mybatis:
  mapper-locations: classpath:mapper/*.xml
tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  client:
    manager-address: 127.0.0.1:9070
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
logging:
  level:
     com.codingapi.txlcn : DEBUG